version: '3.4'

services:
  api:
    environment:
      - SECRET-KEY=verysecretkey
    image: license_plate/docker-license-plate:latest
    container_name: docker-license-plate
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
